server:
  port: 8888
  servlet:
    context-path: /cl-msw
spring:
  # datasource
  datasource:
    url: jdbc:mysql://cl-mysql.mysql.rds.aliyuncs.com:3306/msw_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: msw_dev1
    password: msw_dev1
  # redis
  redis:
    host: 118.178.181.189
    port: 6379
    database: 0
logging:
  level: {com.cl.msw: debug}

